server:
  port: 8005

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.31.204:3306/mall_wms
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis-plus:
  globalConfig:
    dbConfig:
      idType: auto